### ISSUE TITLE
Multiple error emits when used as a channel factory

### ISSUE THREAD

**Issue by mgcrea** [juliangruber/multipipe#11]
With the following factory pattern setup:
```
  function lessChannel() {
    return require('multipipe')(
      less(),
      autoprefixer('last 1 version'),
      gulp.dest(src.tmp)
    );
  };

  gulp.task('src/styles', function() {
    gulp.src(src.styles, {cwd: src.cwd, base: src.cwd})
      .pipe(plumber())
      .pipe(lessChannel());
  });
```
I end up with error event being emitted multiple times (plumber does log errors twice).

It does work with the `stream-combine` module.

**Comment by juliangruber** [comment]
if it's `plumer` that emits errors, that isn't even handled by multipipe

**Comment by callumacrae** [comment]
gulp-plumber works by overwriting the `.pipe` method, I don't actually see any reason why it shouldn't work with multipipe: https://github.com/floatdrop/gulp-plumber/blob/master/index.js#L56

**Comment by juliangruber** [comment]
closing for lack of interest
