### ISSUE TITLE
add test for .destroy()

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/multipipe#20]
if a stream is destroyed, will the end callback still be called?

**Comment by deanlandolt** [comment]
Answer: [nope](https://github.com/deanlandolt/multipipe/commit/0b6eafa484e661b30ce129e9c9c572d8ce9f61ad#diff-ff14352737ca6fead0a89e29b52f1d32R136) -- at least, not if `destroy` wasn't passed an error arg (in that test the callback is never invoked).

[This branch](https://github.com/deanlandolt/multipipe/tree/destroyables) has some additional tests. One possible fix would be to add a `close` handler to all streams that emits an error event w/ something like `new Error('stream closed')` -- would that make sense?

**Comment by juliangruber** [comment]
ah, I remember now that `.destroy()` is a non spec function. For example, through2 implements it by emitting the `"close"` event, which already works with multipipe.

since it's non spec, I vote for the user to implement this by manually emitting an `"error"` event. Afaik there's no way to tell whether a `"close"` event was emitted by aborting a stream or just the usual flow.

What do you think?

**Comment by deanlandolt** [comment]
It's the `close` event that I'm concerned about -- it just so happens that the `destroy` method is one common way to get a `close` event w/o emitting an `error`. I just used `through2Another way: https://github.com/nodejs/node/blob/master/lib/net.js#L436

**Comment by juliangruber** [comment]
https://github.com/juliangruber/multipipe/commit/265fecbbb8b59c750cef11f4d98789a573740f42, published as 0.2.1

**Comment by juliangruber** [comment]
i also added another passing test, feel free to reopen when this doesn't fix your use of the module
