### ISSUE TITLE
multipipe crashes process on nodejs 0.10 (due duplexer2 error)

### ISSUE THREAD

**Issue by okv** [juliangruber/multipipe#30]
Hi, there.

Using multipipe we've encountered an error on nodejs 0.10.
That error https://github.com/deoxxa/duplexer2/issues/23 related to duplexer2, not multipipe itself.
It makes multipipe unusable on nodejs 0.10.

Using [duplexer](https://github.com/Raynos/duplexer) solves the problem for multipipe (i've tried that).

@juliangruber is it acceptable option for you to move on duplexer?

**Comment by juliangruber** [comment]
duplexer is using streams@1, while duplexer2 is using streams@2. streams@2 are a definitive improvement so it's worth keeping this approach.

in my view the way to go is to fix this bug in duplexer2

**Comment by juliangruber** [comment]
this error doesn't happen starting at node 0.12. so i suggest you upgrade your node versions, 0.10 is quite old

**Comment by okv** [comment]
nodejs 0.10 still widely used across different environments (e.g. it's default in openshift service, ubuntu lts, centos, etc). It's nothing good about dropping support of it.

**Comment by juliangruber** [comment]
you're free to submit a pull request that fixes it without dropping streams@2 support

**Comment by okv** [comment]
ok, got it
