### ISSUE TITLE
Optional callback parameter interprets objects emitted with 'close' or 'finish' as errors

### ISSUE THREAD

**Issue by gogwilt** [juliangruber/multipipe#37]
Ran into an issue with the optional callback parameter while promisifying with [Bluebird's `fromNode` method](http://bluebirdjs.com/docs/api/promise.fromcallback.html)

```
Promise.fromNode((cb) => multipipe(streamA, streamB, cb))
```

The issue seemed to be that either the 'close' or 'finish' event was being emitted with a parameter, which was interpreted as an error, and passed into the callback.

The last stream was a write stream created using [`grid-fs-stream`](https://github.com/aheckmann/gridfs-stream), but a repro could be achieved by piping through your own stream that emits a parameter with a 'close' or 'finish' event.

**Comment by juliangruber** [comment]
fixed in 1.0.2

**Comment by gogwilt** [comment]
Thanks!
