### ISSUE TITLE
Http response stream gets not flushed?

### ISSUE THREAD

**Issue by ataube** [juliangruber/multipipe#38]
I am trying to use multipipe in a http server context, something like this:

```
const express = require('express');
const pipe = require('multipipe');
const JSONStream = require('JSONStream');
const app = express();

app.post('/', (req, res, next) => {
  const pipeline = pipe(JSONStream.parse(), JSONStream.stringify(false));
  pipeline.on('error', next);

  req.pipe(pipeline).pipe(res);
});

app.listen(3000, () => {  console.log('Server started...') });
```

`curl -i -X POST -d '{ "hello": "world" }' http://localhost:3000`

```
HTTP/1.1 200 OK
X-Powered-By: Express
Date: Sat, 31 Dec 2016 10:57:41 GMT
Connection: keep-alive
Transfer-Encoding: chunked

[
```
For some reason the http response starts sending the http headers and stops on the body. The connection stays open and the response gets never ended/flushed. Can you/somebody explain this behaviour? If you for instance include the `res` object in the pipeline and remove the last pipe call everything works as expected. But why? I would like to configure my pipeline without the res included...

**Comment by juliangruber** [comment]
this looks like an issue with duplexer2. Can you open it there? Just replace

```js
const pipeline = pipe(JSONStream.parse(), JSONStream.stringify(false));
```

with

```js
const duplex = require('duplexer2')
const parse = JSONStream.parse()
const stringify = JSONStream.stringify(false)
const pipeline = duplex(parse, stringify)
parse.pipe(stringify)
```

**Comment by ataube** [comment]
Thanks @juliangruber for the quick feedback I created an issue on the duplexer2 side.
