### ISSUE TITLE
Why duplexer2 calling with bubbleErrors equal false?

### ISSUE THREAD

**Issue by Serpan911** [juliangruber/multipipe#47]
Hey.

Error handling does not work how it written in the documentation. If the first stream writable and last stream readable, they wrap in duplexer2 with "bubbleErrors" option equal false (by default).

Multipipe will not emit error, in this example:

```js
var multipipe = require('multipipe'); // 1.0.2 version
var JSONStream = require('JSONStream');
var through2 = require('through2');
var https = require('https');

writableStream = through2(function(data, enc, callback) {
	callback(null, data);
});

https.get('https://github.com/juliangruber/multipipe/blob/master/Readme.md', function(res) {
	res.pipe(writableStream);
});

var readableStream = JSONStream.parse('*');

readableStream.on('error', function(err) {
	// it works
	console.log('Readble stream ERROR: ', err);
});

var testStream = multipipe(
	writableStream,
	readableStream
).on('error', function(err) {
	// it not works
	console.log('Multipipe ERROR: ', err)
});
```

Why is this done?

**Comment by juliangruber** [comment]
In this line we should make sure that any stream that isn't the returned stream (which in this case none is) will forward its errors to the returned stream:

https://github.com/juliangruber/multipipe/blob/50ca690e9edd5889dae2105b87618176aa3cc42b/index.js#L62

This seems to be an issue with JSONStream, see https://github.com/dominictarr/JSONStream/issues/136

I modified your script to not use JSONStream but a regular stream that emits an error event, and that is properly caught by multipipe:

```js
var {PassThrough} = require('stream')
var multipipe = require('multipipe'); // 1.0.2 version
var through2 = require('through2');
var https = require('https');

writableStream = through2(function(data, enc, callback) {
  callback(null, data);
});

https.get('https://github.com/juliangruber/multipipe/blob/master/Readme.md', function(res) {
  res.pipe(writableStream);
});

var readableStream = new PassThrough()
setImmediate(() => readableStream.emit('error', new Error('bloob')))

multipipe(
  writableStream,
  readableStream
).on('error', function(err) {
  // it not works
  console.log('Multipipe ERROR: ', err)
});
```

**Comment by anton-makarov** [comment]
JSONStream throws error ok, the problem is in duplexer2. If read stream doesn't implement `read` method, duplexer wraps it in Readable from `readable-stream` lib:
```js
  if (typeof readable.read !== "function") {
    readable = (new stream.Readable(options)).wrap(readable);
  }
```
and in wrap function listeners on all event are applied:
```js
  // proxy certain important events.
  for (var n = 0; n < kProxyEvents.length; n++) {
    stream.on(kProxyEvents[n], this.emit.bind(this, kProxyEvents[n]));
  }
```
But, if `bubbleErrors` hasn't been passed, then no error listeners will be applied to wrapped stream and in case of error in read stream, error will be thrown right into process, crashing everything. Listeners in multipipe don't help because they are applied after listeners in wrap function.

Right now don't know how to fix it, other then to pass `bubbleErrors` in options, but it doesn't feel as the right way :(

**Comment by juliangruber** [comment]
I'll take another look!

**Comment by okv** [comment]
thanks, will be waiting for your news

**Comment by Serpan911** [comment]
Thanks
publish new version please)

**Comment by okv** [comment]
awesome, thanks
